# name: Deploy Production 

# on:
#   push:
#     branches:
#       - main  

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: prod  # ✳️ שם הסביבה – אם הגדרת אחרת בגיטהאב (Settings → Environments), תשני פה

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4

#       - name: Load environment
#         run: echo "${{ secrets.PROD_ENV_FILE }}" > .env  # ✳️ ודאי שהוספת את הסוד PROD_ENV_FILE בגיטהאב → Settings → Secrets

#       - name: Install deps with Yarn
#         run: yarn install  # ✳️ אם את משתמשת ב־Yarn Workspaces – זה מצוין

#       - name: Build all workspaces
#         run: yarn build  # ✳️ ודאי שיש לך סקריפט build בשורש שמבצע build לכל החבילות

#       - name: Run tests (optional)
#         run: yarn test  # ✳️ אם אין בדיקות עדיין, אפשר למחוק שלב זה או לשים סקריפט ריק זמני

#       - name: Upload files to server
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.PROD_SERVER_HOST }}       # ✳️ כתובת ה-IP או ה־domain של השרת שלך (לשמור כ־Secret)
#           username: ${{ secrets.PROD_SERVER_USER }}   # ✳️ שם המשתמש ב־SSH (למשל: ubuntu) – לשמור כ־Secret
#           key: ${{ secrets.PROD_SERVER_SSH_KEY }}     # ✳️ מפתח פרטי (private SSH key) – לשמור כ־Secret
#           port: 22
#           source: "."                                 # ✳️ מה להעלות לשרת – כרגע כל הפרויקט
#           target: "/var/www/tefillin-project"         # ✳️ הנתיב בשרת שאליו תעלה את הקוד שלך

#       - name: Restart app on server
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.PROD_SERVER_HOST }}       # ✳️ שוב כתובת השרת
#           username: ${{ secrets.PROD_SERVER_USER }}   # ✳️ שוב המשתמש ב־SSH
#           key: ${{ secrets.PROD_SERVER_SSH_KEY }}     # ✳️ שוב המפתח
#           port: 22
#           script: |
#             cd /var/www/tefillin-project               # ✳️ ודאי שזה אותו נתיב כמו ב־scp למעלה
#             yarn install
#             yarn build
#             pm2 restart tefillin-app || pm2 start packages/tefillin-backend/index.js --name tefillin-app  
#             # ✳️ ודאי שזה הנתיב לקובץ שמריץ את השרת שלך, ושם האפליקציה ב־PM2
